name: CI
on: [pull_request]

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - uses: Swatinem/rust-cache@1a8384176d7ed15c323a201c65073983cdb5a5be

      - name: Run build
        run: cargo run -p xtask -- build

      - name: Run all tests
        run: cargo run -p xtask -- test
