name: CI
on: [pull_request]

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - uses: Swatinem/rust-cache@d7ac6f694df60fb8ce48bab7b59ad5da1ac8d46e

      - name: Run build
        run: cargo run -p xtask -- build

      - name: Run all tests
        run: cargo run -p xtask -- test
